<?php
$prefixe = "/faq-fmi";
$t_copyright="&#169;Copyright 2015 S&eacute;bastien Grillon - Ligue du Centre de Football"; //figure en bas de chaque page
$t_titre_site = "FAQ Feuille de Match Informatis&eacute;e"; //figure dans le titre du navigateur sur chaque page (<head><title>)
$t_titre_banniere = "FAQ FMI"; //figure dans le fichier entete de page
$t_invit_connexion = "Saisissez votre nom d'utilisateur et votre mot de passe pour vous connecter :"; //invite sur la page accueil.php
$t_username = "Nom d'utilisateur :";
$t_password = "Mot de passe :";
$t_form_probleme = "Veuillez renseigner votre probl&egrave;me :";
$t_form_p1 ="Nom :";
$t_form_p2 ="Pr&eacute;nom :";
$t_form_p3 ="Club :";
$t_form_p4 ="R&ocirc;le :";
$t_form_p5 ="T&eacute;l&eacute;phone :";
$t_form_p6 ="Email :";
$t_form_p7 ="Date du match :";
$t_form_p8 ="Club recevant :";
$t_form_p9 ="Club visiteur :";
$t_form_p10 ="Gestionnaire comp&eacute;tition :";
$t_form_p11 ="Cat&eacute;gorie :";
$t_form_p12 ="Comp&eacute;tition :";
$t_form_p13 ="Poule :";
$t_form_p14 ="Support :";
$t_form_p15 ="Rubrique :";
$t_form_p16 ="Etape :";
$t_form_p17 ="Descriptif :";
$t_chapeau_faq = "Bienvenue sur la FAQ d&eacute;di&eacute;e &agrave; la Feuille de Match Informatis&eacute;e.<br>Vous trouverez ci-dessous les probl&egrave;mes rencontr&eacute;s couramment et les solutions que l'on peut y apporter.<br>Si votre probl&egrave;me n'appara&icirc;t pas, vous pouvez nous le soumettre gr&acirc;ce au formulaire en bas de page.";
$t_form_non_renseigne ="Le formulaire est vide ou incomplet, veuillez le remplir compl&egrave;tement avant de cliquer sur le bouton Valider :<br><br>";
$t_etat1 = "1 - Soumis";
$t_etat2 = "2 - Propos&eacute;";
$t_etat3 = "3 - Accept&eacute;";
$t_etat4 = "4 - Pr&eacute;par&eacute;";
$t_etat5 = "5 - Valid&eacute;";
$t_etat6 = "6 - Publi&eacute;";
$t_form_reussi = "Votre probl&egrave;me a &eacute;t&eacute; soumis avec succ&egrave;s. Nous vous r&eacute;pondrons dans les meilleurs d&eacute;lais.<br><br>";
?>